name: app
publish_to: "none"
description: "ChatBot"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
