name: chatbot
version: 0.0.5+1
publish_to: "none"
description: "ChatBot"

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  markdown: ^7.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  flutter_markdown: ^0.7.4+1
  flutter_highlighter: ^0.1.1
  flutter_image_compress: ^2.3.0
  flutter_markdown_latex: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
